[profile.default]
src = "src"
out = "out"
libs = ["dependencies"]
gas_reports = ['*']
solc_version = "0.8.30"
optimizer = true
optimizer_runs = 10_000
via_ir = true
ffi = true
ast = true
build_info = true
extra_output = ["storageLayout"]
dynamic_test_linking = true
fs_permissions = [{ access = "read-write", path = "." }]

[profile.deploy]
optimizer_runs = 10_000

[profile.solx]
optimization = 3
gas_limit = 100_000_000

[lint]
exclude_lints = ["mixed-case-function","screaming-snake-case-immutable","pascal-case-struct", "mixed-case-variable"]
                    
[fuzz]
runs = 1000
max_test_rejects = 65536
seed = '0x1'
dictionary_weight = 40
include_storage = true
include_push_bytes = true
extra_output = ["storageLayout", "metadata"]

[invariant]
runs = 256
depth = 128
fail_on_revert = true
call_override = false
preserve_state = true   

[fmt]
bracket_spacing = true
int_types = "long"
line_length = 120
multiline_func_header = "all"
number_underscore = "thousands"
quote_style = "double"
tab_width = 4
wrap_comments = true
sort_imports = true

[rpc_endpoints]
mainnet = "${RPC_MAINNET}"
sepolia = "${RPC_SEPOLIA}"

[etherscan]
mainnet = { key = "${ETHERSCAN_MAINNET_KEY}" }

[doc]
out = "foundry-docs/"
title = "KAM Contracts Documentation"
ignore = [
    "src/vendor/**",
]


[dependencies]
forge-std = "1.9.7"

[soldeer]
# whether soldeer manages remappings
remappings_generated = false
# whether soldeer re-generates all remappings when installing, updating or uninstalling deps
remappings_regenerate = false
# whether to suffix the remapping with the version: `name-a.b.c`
remappings_version = false
